import { PrecomplianceEventType as eventTypes } from "./constants";

export interface CrushSuiteConfig {
  privateKey: string;
  sandboxKey?: string;
  _environment?: "production" | "staging";
}

export interface CrushSuiteAPI {
  compliance: {
    complianceEvent(
      eventData: PrecomplianceEvent
    ): Promise<PrecomplianceEventResponse>;
    prepurchaseCompliance(
      complianceData: OrderCheckComplianceRequest
    ): Promise<OrderCheckComplianceResponse>;
    alcoholFee(
      complianceData: OrderCheckComplianceFeeRequest
    ): Promise<OrderCheckComplianceFeeResponse>;
  };
}

/**
 * Precompliance event types
 * These are generated by Prisma and used to track the precompliance process.
 */
export type PrecomplianceEventType =
  (typeof eventTypes)[keyof typeof eventTypes];

/** Order compliance types
 * These types are used for checking compliance of orders
 * and for the precompliance process.
 */
export type OrderCheckComplianceAddress = {
  firstName: string;
  lastName: string;
  businessName?: string; // Optional for business addresses
  street1: string;
  street2?: string;
  city: string;
  postalCode: string;
  stateCode: string;
  country: string; // 2 letter country code, e.g. 'US', 'CA'
};

export type OrderCheckComplianceDOB = {
  day: number;
  month: number;
  year: number;
};

export type OrderCheckComplianceRequest = {
  variants: { id: number; quantity: number }[];
  billToAddress: OrderCheckComplianceAddress;
  shipToAddress: OrderCheckComplianceAddress;
  dob: OrderCheckComplianceDOB;
  email: string;
  phoneNumber: string; // Must be 10-digit US phone number
};

export type ComplianceFee = { [key: VariantId]: Quantity };

type VariantId = number;
type Quantity = number;

export interface Compliance {
  valid: boolean;
  errors: string[];
}

export interface OrderCheckComplianceResponse {
  valid: boolean;
  complianceFee: ComplianceFee | null;
  complianceKey: string | null;
  errors: string[];
}

export type OrderCheckComplianceFeeRequest = {
  shippingStateCode: string; // 2 letter state code, e.g. 'OR', 'CA', 'NY'
  variants: { id: number; quantity: number }[];
};

export interface OrderCheckComplianceFeeResponse {
  fee: ComplianceFee | null;
  total: number;
}

export interface PurchasedOrderItem {
  productType: string;
  name: string;
  quantity: number;
  isComplianceProduct: boolean;
  isVinoshipperProduct: boolean;
  isDbProduct: boolean;
  compliancePartnerProductId: string;
  platformVariantId: string;
  dbProductId: number;
}

export interface PrecomplianceEvent {
  sessionId: string;
  eventType: PrecomplianceEventType;
  failedReason?: string;
  failedPayload?: string; // JSON
  failedUser?: string; // JSON
}

export type PrecomplianceEventResponse = {
  message: string;
};

// this gets saved to redis
export interface PrecomplianceCustomer {
  email: string;
  firstName: string;
  lastName: string;
  address: {
    street1: string;
    street2?: string | null;
    city: string;
    postalCode: string;
    stateCode: string;
  };
  dateOfBirth: PrecomplianceCustomerDOB;
}

export type PrecomplianceCustomerDOB = {
  day: number;
  month: number;
  year: number;
};
