export const CART_CUSTOMER_DOB = "customer_dob__";
export const CART_VALID_COMPLIANCE_ID = "valid_compliance_id__";

export const CRUSHSUITE_SHIPPING_STATE = "CRUSHSUITE_SHIPPING_STATE" as const;
export const CRUSHSUITE_AGE_VERIFIED = "CRUSHSUITE_AGE_VERIFIED" as const;

export const CRUSHSUITE_CUSTOMER_DEFAULT_ADDRESS =
  "CRUSHSUITE_CUSTOMER_DEFAULT_ADDRESS" as const;

export const CRUSHSUITE_CUSTOMER_DOB = "CRUSHSUITE_CUSTOMER_DOB" as const;
